# Generated by Django 4.2 on 2023-05-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_brand', models.CharField(choices=[('BMW', 'BMW'), ('Subaru', 'Subaru'), ('Mini', 'Mini'), ('Lexus', 'Lexus'), ('Honda', 'Honda'), ('Toyota', 'Toyota'), ('Genesis', 'Genesis'), ('Mazda', 'Mazda'), ('Audi', 'Audi'), ('Kia', 'Kia'), ('Acura', 'Acura'), ('Buick', 'Buick'), ('Hyundai', 'Hyundai'), ('Porsche', 'Porsche'), ('Dodge', 'Dodge'), ('Lincoln', 'Lincoln'), ('Tesla', 'Tesla'), ('Infiniti', 'Infiniti'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Nissan', 'Nissan'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Cadillac', 'Cadillac'), ('Chrysler', 'Chrysler'), ('Mercedes-Benz', 'Mercedes-Benz'), ('GMC', 'GMC'), ('Mitsubishi', 'Mitsubishi'), ('Alfa Romeo', 'Alfa Romeo'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Land Rover', 'Land Rover')], max_length=100)),
                ('Year', models.PositiveIntegerField()),
                ('Mileage', models.PositiveIntegerField()),
                ('fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('EV', 'Electric Vehicle'), ('Diesel', 'Diesel')], max_length=100)),
                ('Valuation', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
