# Generated by Django 4.2 on 2023-06-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0002_rename_mileage_vehicle_distance_travelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Fuel',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_brand',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_name',
            field=models.CharField(choices=[('BMW', 'BMW'), ('Subaru', 'Subaru'), ('Mini', 'Mini'), ('Lexus', 'Lexus'), ('Honda', 'Honda'), ('Toyota', 'Toyota'), ('Genesis', 'Genesis'), ('Mazda', 'Mazda'), ('Audi', 'Audi'), ('Kia', 'Kia'), ('Acura', 'Acura'), ('Buick', 'Buick'), ('Hyundai', 'Hyundai'), ('Porsche', 'Porsche'), ('Dodge', 'Dodge'), ('Lincoln', 'Lincoln'), ('Tesla', 'Tesla'), ('Infiniti', 'Infiniti'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Nissan', 'Nissan'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Cadillac', 'Cadillac'), ('Chrysler', 'Chrysler'), ('Mercedes-Benz', 'Mercedes-Benz'), ('GMC', 'GMC'), ('Mitsubishi', 'Mitsubishi'), ('Alfa Romeo', 'Alfa Romeo'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Land Rover', 'Land Rover')], max_length=100),
        ),
    ]
